name: Auto Update live.m3u

on:
  push:
    branches:
      - main
      - test-trigger
  schedule:
    - cron: '*/1 * * * *'  # 每分钟一次

jobs:
  update-file:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: |
        python extract_9901.py

    - name: Commit changes
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add live.m3u
        git commit -m 'Update live.m3u with new 9901 port addresses'
        git push https://$ACTIONS_DEPLOY_KEY@github.com/${{ github.repository }}.git HEAD:main
